/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.99.0
  Forc version: 0.66.7
  Fuel-Core version: 0.40.0
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "[[u256; 2]; 2]",
      "concreteTypeId": "7773744b695a84b77e0d78e7a2c64ee6f87a38e0d24a585ec3d3a653188f203d",
      "metadataTypeId": 2
    },
    {
      "type": "[u256; 1]",
      "concreteTypeId": "d260603a6118f4d090787a9d1cc94f3afade594c02f0049f0f856f4d5285d980",
      "metadataTypeId": 0
    },
    {
      "type": "[u256; 2]",
      "concreteTypeId": "56fef9f25ffc1d2c2a7f2fea34dfee194ce23e79ccb0ab6044fdc267813390da",
      "metadataTypeId": 1
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    }
  ],
  "metadataTypes": [
    {
      "type": "[_; 1]",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__array_element",
          "typeId": 3
        }
      ]
    },
    {
      "type": "[_; 2]",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "__array_element",
          "typeId": 3
        }
      ]
    },
    {
      "type": "[_; 2]",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "__array_element",
          "typeId": 1
        }
      ]
    },
    {
      "type": "u256",
      "metadataTypeId": 3
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "p_a",
          "concreteTypeId": "56fef9f25ffc1d2c2a7f2fea34dfee194ce23e79ccb0ab6044fdc267813390da"
        },
        {
          "name": "p_b",
          "concreteTypeId": "7773744b695a84b77e0d78e7a2c64ee6f87a38e0d24a585ec3d3a653188f203d"
        },
        {
          "name": "p_c",
          "concreteTypeId": "56fef9f25ffc1d2c2a7f2fea34dfee194ce23e79ccb0ab6044fdc267813390da"
        },
        {
          "name": "pub_signals",
          "concreteTypeId": "d260603a6118f4d090787a9d1cc94f3afade594c02f0049f0f856f4d5285d980"
        }
      ],
      "name": "verify_proof",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [];

export class SwayVerifierInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    verify_proof: FunctionFragment;
  };
}

export class SwayVerifier extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: SwayVerifierInterface;
  declare functions: {
    verify_proof: InvokeFunction<[p_a: [BigNumberish, BigNumberish], p_b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], p_c: [BigNumberish, BigNumberish], pub_signals: [BigNumberish]], boolean>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
